#!/bin/sh
#stop and remove vault containers if already running
docker stop vault-demo-vault
docker rm vault-demo-vault



#start Vault in dev mode on port 8200
#docker run --name vault-demo-vault -e 'VAULT_LOCAL_CONFIG={"storage": {"raft": {"path": "/vault/file", "node_id" : "raft_node_1"}}, "listener": [{"tcp": { "address": "0.0.0.0:8200", "tls_disable": true}}], "ui": true, "cluster_addr" : "https://127.0.0.1:8201", "license" : "02MV4UU43BK5HGYYTOJZWFQMTMNNEWU33JJZKGY222K5ITAT2HKF2E2MSRPBHHSMDXJV5GWMCMKRFGWTJSIV2FUVCBGJGXUWTKLJKGGMSZNJJGUSLJO5UVSM2WPJSEOOLULJMEUZTBK5IWST3JJJVFUVCBPBGW2WJULF4TA6KZPJTXUTCXJUYU6RCJORNG2SLZLF4TAM2ZGJJGUTT2IV3U4V2JPJNEI23JJRBUU4DCNZHDAWKXPBZVSWCSOBRDENLGMFLVC2KPNFEXCSLJO5UWCWCOPJSFOVTGMRDWY5C2KNETMSLKJF3U22SNORGUIRLUJVKGYVKNKRGTMTL2KE3E4VCVOVHHUQJUJ5KGWNKOIRATKV3JJFZUS3SOGBMVQSRQLAZVE4DCK5KWST3JJF4U2RCJPJGFIQLYJRKEKNKWIRAXOT3KIF3U62SBO5LWSSLTJFWVMNDDI5WHSWKYKJYGEMRVMZSEO3DULJJUSNSJNJEXOTLKKF2E2RCFORGVI3CVJVVE2NSOKRVTMTSUNN2U6VDLGVLWSSLTJFXFE3DDNUYXAYTNIYYGCVZZOVMDGUTQMJLVK2KPNFEXSTKEJEYEYVCBPBGFIRJVKZCES6SPNJKTKT3KKU2UY2TLGVHVM33JJRBUU53DNU4WWZCXJYYES2TPNFSG2RRRMJEFC2KMINFG2YSHIZXGG6KJGZSXSSTUMIZFEMLCI5LHUSLKOBRES3JRGFREQUTQJRLVE2SMLBHGUWKXPBWES2LXNFNDEOJSLJMEU5KZK42WUWSTGF3WEMTYOBMTG23JJRBUU2C2JBNGQYTNJZWFUQZRNNMVQUTIJRMEE6LCGNJGYWJTKJYGEMRUORSEQSTIMJXE43LCGNFHISLJO5UVSV2SGJMVONLKLJLVC5C2I5DDAWKTGF3WG3JZGBNFOTRQMFLTS5KMK52GYZKTGF2FSVZVNBNDEVTULJLTKMCJNQYTSZSRHU6S4SSWOJVXSZ2XJ53DGZLRGNIGMRLCJF5GMNTWJNYUGUTTJRFTKTLNNN3EMRKDINSUQMJLPFTWYVDKKN4EU3LENEYU6R2QNM3GKSZTI5XEO3ZYKZCWM3KBOVIDINCFNZNEINDTKNXUESRRMRAWWY3BGRSFMMBTGM4FA53NKZWGC5SKKA2HASTYJFETSRBWKVDEYVLBKZIGU22XJJ2GGRBWOBQWYNTPJ5TEO3SLGJ5FAS2KKJWUOSCWGNSVU53RIZSSW3ZXNMXXGK2BKRHGQUC2M5JS6S2WLFTS6SZLNRDVA52MG5VEE6CJG5DU6YLLGZKWC2LBJBXWK2ZQKJKG6NZSIRIT2PI"}' --network dev-network -p 8200:8200 --cap-add IPC_LOCK hashicorp/vault-enterprise server -dev -dev-root-token-id="root" &

docker run --name vault-demo-vault  --network dev-network -p 8200:8200 hashicorp/vault-enterprise:1.4.0_ent server -dev -dev-root-token-id="root" &


